
class EditorDomCache {
    root: Document | HTMLElement;
    editorCanvas: HTMLCanvasElement | null;
    mapPosition: HTMLElement | null;
    mapNavButtons: HTMLElement[];
    mobileNavButtons: HTMLElement[];
    mobilePanels: HTMLElement[];
    selectedTilePreview: HTMLElement | null;
    tileSummary: HTMLElement | null;
    tileList: HTMLElement | null;
    npcsList: HTMLElement | null;
    npcText: HTMLTextAreaElement | null;
    npcConditionalText: HTMLTextAreaElement | null;
    npcConditionalVariable: HTMLSelectElement | null;
    npcRewardVariable: HTMLSelectElement | null;
    npcConditionalRewardVariable: HTMLSelectElement | null;
    btnToggleNpcConditional: HTMLElement | null;
    npcConditionalSection: HTMLElement | null;
    npcVariantButtons: HTMLElement[];
    worldGrid: HTMLElement | null;
    titleInput: HTMLInputElement | null;
    authorInput: HTMLInputElement | null;
    fileInput: HTMLInputElement | null;
    objectTypes: HTMLElement | null;
    objectsList: HTMLElement | null;
    btnNpcDelete: HTMLElement | null;
    npcEditor: HTMLElement | null;
    btnGenerateUrl: HTMLElement | null;
    shareUrlInput: HTMLInputElement | null;
    btnUndo: HTMLElement | null;
    btnRedo: HTMLElement | null;
    enemyTypes: HTMLElement | null;
    enemiesList: HTMLElement | null;
    projectVariablesContainer: HTMLElement | null;
    projectVariablesToggle: HTMLElement | null;
    projectVariableList: HTMLElement | null;
    projectVariableSummary: HTMLElement | null;
    projectSkillsContainer: HTMLElement | null;
    projectSkillsToggle: HTMLElement | null;
    projectSkillsList: HTMLElement | null;
    projectTestContainer: HTMLElement | null;
    projectTestToggle: HTMLElement | null;
    projectTestPanel: HTMLElement | null;
    projectTestStartLevel: HTMLSelectElement | null;
    projectTestSkillList: HTMLElement | null;
    projectTestGodMode: HTMLInputElement | null;
    projectPaletteContainer: HTMLElement | null;
    projectPaletteToggle: HTMLButtonElement | null;
    projectPalettePanel: HTMLElement | null;
    paletteGrid: HTMLElement | null;
    paletteResetButton: HTMLButtonElement | null;
    colorPickerModal: HTMLElement | null;
    colorPickerInput: HTMLInputElement | null;
    colorPickerConfirm: HTMLButtonElement | null;
    colorPickerCancel: HTMLButtonElement | null;
    colorPreviewCurrent: HTMLElement | null;
    colorPreviewNew: HTMLElement | null;
    colorPickerIndex: HTMLElement | null;
    jsonArea?: HTMLTextAreaElement | null;

    constructor(root: Document | HTMLElement | null = typeof document !== 'undefined' ? document : null) {
        this.root = root || (null as unknown as Document); // fallback for strict mode if needed, though properties can be null
        if (!root) {
            this.editorCanvas = null;
            this.mapPosition = null;
            this.mapNavButtons = [];
            this.mobileNavButtons = [];
            this.mobilePanels = [];
            this.selectedTilePreview = null;
            this.tileSummary = null;
            this.tileList = null;
            this.npcsList = null;
            this.npcText = null;
            this.npcConditionalText = null;
            this.npcConditionalVariable = null;
            this.npcRewardVariable = null;
            this.npcConditionalRewardVariable = null;
            this.btnToggleNpcConditional = null;
            this.npcConditionalSection = null;
            this.npcVariantButtons = [];
            this.worldGrid = null;
            this.titleInput = null;
            this.authorInput = null;
            this.fileInput = null;
            this.objectTypes = null;
            this.objectsList = null;
            this.btnNpcDelete = null;
            this.npcEditor = null;
            this.btnGenerateUrl = null;
            this.shareUrlInput = null;
            this.btnUndo = null;
            this.btnRedo = null;
            this.enemyTypes = null;
            this.enemiesList = null;
            this.projectVariablesContainer = null;
            this.projectVariablesToggle = null;
            this.projectVariableList = null;
            this.projectVariableSummary = null;
            this.projectSkillsContainer = null;
            this.projectSkillsToggle = null;
            this.projectSkillsList = null;
            this.projectTestContainer = null;
            this.projectTestToggle = null;
            this.projectTestPanel = null;
            this.projectTestStartLevel = null;
            this.projectTestSkillList = null;
            this.projectTestGodMode = null;
            this.projectPaletteContainer = null;
            this.projectPaletteToggle = null;
            this.projectPalettePanel = null;
            this.paletteGrid = null;
            this.paletteResetButton = null;
            this.colorPickerModal = null;
            this.colorPickerInput = null;
            this.colorPickerConfirm = null;
            this.colorPickerCancel = null;
            this.colorPreviewCurrent = null;
            this.colorPreviewNew = null;
            this.colorPickerIndex = null;
            this.jsonArea = null;
            return;
        }

        this.editorCanvas = root.querySelector('#editor-canvas') as HTMLCanvasElement | null;
        this.mapPosition = root.querySelector('#editor-map-position') as HTMLElement | null;
        this.mapNavButtons = Array.from(root.querySelectorAll('.map-nav-button'));
        this.mobileNavButtons = Array.from(root.querySelectorAll('.editor-mobile-nav-button'));
        this.mobilePanels = Array.from(root.querySelectorAll('.editor-section[data-mobile-panel]'));
        this.selectedTilePreview = root.querySelector('#selected-tile-preview') as HTMLElement | null;
        this.tileSummary = root.querySelector('#tile-preset-summary') as HTMLElement | null;
        this.tileList = root.querySelector('#tile-list') as HTMLElement | null;
        this.npcsList = root.querySelector('#npcs-list') as HTMLElement | null;
        this.npcText = root.querySelector('#npc-text') as HTMLTextAreaElement | null;
        this.npcConditionalText = root.querySelector('#npc-conditional-text') as HTMLTextAreaElement | null;
        this.npcConditionalVariable = root.querySelector('#npc-conditional-variable') as HTMLSelectElement | null;
        this.npcRewardVariable = root.querySelector('#npc-reward-variable') as HTMLSelectElement | null;
        this.npcConditionalRewardVariable = root.querySelector('#npc-conditional-reward-variable') as HTMLSelectElement | null;
        this.btnToggleNpcConditional = root.querySelector('#btn-toggle-npc-conditional') as HTMLElement | null;
        this.npcConditionalSection = root.querySelector('#npc-conditional-section') as HTMLElement | null;
        this.npcVariantButtons = Array.from(root.querySelectorAll('[data-npc-variant-filter]'));
        this.worldGrid = root.querySelector('#world-grid') as HTMLElement | null;
        this.titleInput = root.querySelector('#game-title') as HTMLInputElement | null;
        this.authorInput = root.querySelector('#game-author') as HTMLInputElement | null;
        this.fileInput = root.querySelector('#file-input') as HTMLInputElement | null;
        this.objectTypes = root.querySelector('#object-types') as HTMLElement | null;
        this.objectsList = root.querySelector('#objects-list') as HTMLElement | null;
        this.btnNpcDelete = root.querySelector('#npc-delete') as HTMLElement | null;
        this.npcEditor = root.querySelector('.npc-editor') as HTMLElement | null;
        this.btnGenerateUrl = root.querySelector('#btn-generate-url') as HTMLElement | null;
        this.shareUrlInput = root.querySelector('#project-share-url') as HTMLInputElement | null;
        this.btnUndo = root.querySelector('#btn-undo') as HTMLElement | null;
        this.btnRedo = root.querySelector('#btn-redo') as HTMLElement | null;
        this.enemyTypes = root.querySelector('#enemy-types') as HTMLElement | null;
        this.enemiesList = root.querySelector('#enemies-list') as HTMLElement | null;
        this.projectVariablesContainer = root.querySelector('#project-variables-container') as HTMLElement | null;
        this.projectVariablesToggle = root.querySelector('#project-variables-toggle') as HTMLElement | null;
        this.projectVariableList = root.querySelector('#project-variable-usage-list') as HTMLElement | null;
        this.projectVariableSummary = root.querySelector('#project-variable-usage-summary') as HTMLElement | null;
        this.projectSkillsContainer = root.querySelector('#project-skills-container') as HTMLElement | null;
        this.projectSkillsToggle = root.querySelector('#project-skills-toggle') as HTMLElement | null;
        this.projectSkillsList = root.querySelector('#project-skills-list') as HTMLElement | null;
        this.projectTestContainer = root.querySelector('#project-test-container') as HTMLElement | null;
        this.projectTestToggle = root.querySelector('#project-test-toggle') as HTMLElement | null;
        this.projectTestPanel = root.querySelector('#project-test-panel') as HTMLElement | null;
        this.projectTestStartLevel = root.querySelector('#project-test-start-level') as HTMLSelectElement | null;
        this.projectTestSkillList = root.querySelector('#project-test-skill-list') as HTMLElement | null;
        this.projectTestGodMode = root.querySelector('#project-test-god-mode') as HTMLInputElement | null;
        this.projectPaletteContainer = root.querySelector('#project-palette-container') as HTMLElement | null;
        this.projectPaletteToggle = root.querySelector('#project-palette-toggle') as HTMLButtonElement | null;
        this.projectPalettePanel = root.querySelector('#project-palette-panel') as HTMLElement | null;
        this.paletteGrid = root.querySelector('#palette-grid') as HTMLElement | null;
        this.paletteResetButton = root.querySelector('#palette-reset-button') as HTMLButtonElement | null;
        this.colorPickerModal = root.querySelector('#color-picker-modal') as HTMLElement | null;
        this.colorPickerInput = root.querySelector('#color-picker-input') as HTMLInputElement | null;
        this.colorPickerConfirm = root.querySelector('#color-picker-confirm') as HTMLButtonElement | null;
        this.colorPickerCancel = root.querySelector('#color-picker-cancel') as HTMLButtonElement | null;
        this.colorPreviewCurrent = root.querySelector('#color-preview-current .color-preview-swatch') as HTMLElement | null;
        this.colorPreviewNew = root.querySelector('#color-preview-new .color-preview-swatch') as HTMLElement | null;
        this.colorPickerIndex = root.querySelector('#color-picker-index') as HTMLElement | null;
        this.jsonArea = root.querySelector('#json-area') as HTMLTextAreaElement | null;
    }
}

export { EditorDomCache };
