import { GameStateLifecycle } from './state/GameStateLifecycle';
import { GameStateScreenManager } from './state/GameStateScreenManager';
import { GameStateDataFacade } from './state/GameStateDataFacade';
import { GameStateWorldFacade } from './state/GameStateWorldFacade';
import { StateDataManager } from './state/StateDataManager';
import { StateDialogManager } from './state/StateDialogManager';
import { StateEnemyManager } from './state/StateEnemyManager';
import { StateItemManager } from './state/StateItemManager';
import { StateObjectManager } from './state/StateObjectManager';
import { StatePlayerManager } from './state/StatePlayerManager';
import { StateSkillManager } from './state/StateSkillManager';
import { StateVariableManager } from './state/StateVariableManager';
import { StateWorldManager } from './state/StateWorldManager';
import type { TileMap } from './definitions/tileTypes';
import type { DialogMeta, DialogState, EnemyDefinition, GameDefinition, LevelUpChoice, LevelUpCelebrationHideOptions, LevelUpCelebrationOptions, LevelUpCelebrationState, LevelUpOverlayState, LevelUpResult, PickupOverlayOptions, PickupOverlayState, PlayerRuntimeState, ReviveSnapshot, RoomDefinition, RuntimeState, TestSettings } from '../../types/gameState';
/**
 * GameState stores the persistent game definition and runtime state.
 */
declare class GameState {
    game: GameDefinition;
    state: RuntimeState;
    testSettings: TestSettings;
    worldManager: StateWorldManager;
    variableManager: StateVariableManager;
    objectManager: StateObjectManager;
    enemyManager: StateEnemyManager;
    skillManager: StateSkillManager;
    playerManager: StatePlayerManager;
    dialogManager: StateDialogManager;
    itemManager: StateItemManager;
    worldFacade: GameStateWorldFacade;
    screenManager: GameStateScreenManager;
    dataManager: StateDataManager;
    dataFacade: GameStateDataFacade;
    playing: boolean;
    lifecycle: GameStateLifecycle;
    reviveSnapshot: ReviveSnapshot | null;
    lastKillerEnemyId: string | null;
    editorMode: boolean;
    constructor();
    createEmptyRoom(size: number, index?: number, cols?: number): RoomDefinition;
    createWorldRooms(rows: number, cols: number, size: number): RoomDefinition[];
    createEmptyTileMap(size: number): TileMap;
    getGame(): GameDefinition;
    getState(): RuntimeState;
    getCurrentRoom(): RoomDefinition;
    getPlayer(): PlayerRuntimeState | null;
    getSkills(): string[];
    hasSkill(skillId: string): boolean;
    getPendingLevelUpChoices(): number;
    getMaxPlayerLevel(): number;
    isLevelUpOverlayActive(): boolean;
    getLevelUpOverlay(): LevelUpOverlayState;
    startLevelUpSelectionIfNeeded(): void;
    queueLevelUpChoices(count?: number, latestLevel?: number | null): number;
    moveLevelUpCursor(delta?: number): number;
    selectLevelUpSkill(index?: number | null): LevelUpChoice | null;
    consumeRecentReviveFlag(): boolean;
    getDialog(): DialogState;
    setPlayerPosition(x: number, y: number, roomIndex?: number | null): void;
    setDialog(active: boolean, text?: string, meta?: DialogMeta | null): void;
    setDialogPage(page: number): void;
    setEditorMode(active?: boolean): void;
    isEditorModeActive(): boolean;
    createDefaultTestSettings(): TestSettings;
    getTestSettings(): TestSettings;
    setTestSettings(settings?: Partial<TestSettings>): TestSettings;
    applyTestSettingsRuntime(): void;
    resetGame(): void;
    exportGameData(): unknown;
    importGameData(data: unknown): void;
    normalizeRooms(rooms: unknown, totalRooms: number, cols: number): unknown;
    normalizeTileMaps(source: unknown, totalRooms: number): unknown;
    normalizeObjects(objects: unknown): unknown;
    cloneEnemies(enemies: unknown): unknown;
    generateObjectId(type: string, roomIndex: number): string;
    getObjects(): unknown;
    getObjectsForRoom(roomIndex: number): unknown;
    getObjectAt(roomIndex: number, x: number, y: number): unknown;
    setObjectPosition(type: string, roomIndex: number, x: number, y: number): unknown;
    removeObject(type: string, roomIndex: number): void;
    setObjectVariable(type: string, roomIndex: number, variableId: string | null): string | null;
    setPlayerEndText(roomIndex: number, text: string): string;
    getPlayerEndText(roomIndex?: number | null): string;
    setActiveEndingText(text?: string): string;
    getActiveEndingText(): string;
    addKeys(amount?: number): number;
    addLife(amount?: number): number;
    addBonusMaxLife(amount?: number): number;
    addDamageShield(amount?: number, type?: null): number;
    getDamageShield(): number;
    getDamageShieldMax(): number;
    getSwordType(): string | null;
    setSwordType(swordType: string | null): void;
    getSwordDurability(): number;
    setSwordDurability(durability: number): void;
    consumeSwordDurability(): boolean;
    getPlayerDamage(): number;
    consumeKey(): boolean;
    getKeys(): number;
    getMaxKeys(): number;
    consumeLastDamageReduction(): number;
    ensureDefaultVariables(): unknown;
    cloneVariables(list: unknown[]): unknown;
    normalizeVariables(source: unknown): unknown;
    getVariableDefinitions(): unknown;
    getVariables(): unknown;
    normalizeVariableId(variableId: string | number | null | undefined): string | null;
    getVariable(variableId: string | number | null | undefined): unknown;
    isVariableOn(variableId: string | number | null | undefined): boolean;
    setVariableValue(variableId: string | number, value: unknown, persist?: boolean): [boolean, boolean];
    getEnemies(): EnemyDefinition[];
    getEnemyDefinitions(): EnemyDefinition[];
    clampRoomIndex(value: number): number;
    clampCoordinate(value: number): number;
    getWorldRows(): number;
    getWorldCols(): number;
    getRoomCoords(index: number): {
        row: number;
        col: number;
    };
    getRoomIndex(row: number, col: number): number | null;
    addEnemy(enemy: EnemyDefinition): string | null;
    removeEnemy(enemyId: string | number): void;
    setEnemyPosition(enemyId: string | number, x: number, y: number, roomIndex?: number | null): void;
    setEnemyVariable(enemyId: string | number, variableId?: string | null): boolean;
    damagePlayer(amount?: number): number;
    isPlayerOnDamageCooldown(): boolean;
    getLives(): number;
    getMaxLives(): number;
    getLevel(): number;
    healPlayerToFull(): number;
    getExperience(): number;
    getExperienceToNext(): number;
    addExperience(amount?: number): LevelUpResult | null;
    handleEnemyDefeated(experienceReward?: number): LevelUpResult | null;
    processLevelUpResult(result?: LevelUpResult | null): LevelUpResult | null;
    getPickupOverlay(): PickupOverlayState;
    showPickupOverlay(options?: PickupOverlayOptions): void;
    hidePickupOverlay(): void;
    isPickupOverlayActive(): boolean;
    getLevelUpCelebration(): LevelUpCelebrationState;
    showLevelUpCelebration(level?: number | null, options?: LevelUpCelebrationOptions): void;
    hideLevelUpCelebration({ skipResume }?: LevelUpCelebrationHideOptions): void;
    isLevelUpCelebrationActive(): boolean;
    getNow(): number;
    enableGameOverInteraction(): void;
    prepareNecromancerRevive(): boolean;
    hasNecromancerReviveReady(): boolean;
    setLastKillerEnemy(enemyId: string | null): void;
    getLastKillerEnemyId(): string | null;
    reviveFromNecromancer(): boolean;
    clearNecromancerRevive(): void;
    captureReviveSnapshot(): ReviveSnapshot | null;
    restoreReviveSnapshot(snapshot?: ReviveSnapshot | null): boolean;
    assignData(target: Record<string, unknown> | null | undefined, source: Record<string, unknown> | null | undefined): void;
    safeClone<T>(value: T): T;
    pauseGame(reason?: string): void;
    resumeGame(reason?: string): void;
    setGameOver(active?: boolean, reason?: string): void;
    isGameOver(): boolean;
    getGameOverReason(): string | null;
    get canResetAfterGameOver(): boolean;
}
export { GameState };
